# Site
name: Tomer Ben David on Programming
description: What I learned last week on programming
meta_description: "What I learned last week on programming."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
paginate: 15

url                      : https://tomer-ben-david.github.io
baseurl                  : tomer-ben-david-mediumish
baseurl: /tomer-ben-david
google_analytics: 'UA-1448968-8'
disqus: 'tomer-ben-david-github-io'
mailchimp-list: 'https://github.us16.list-manage.com/subscribe/post?u=eb784ee630e214e34a5f9ad9d&amp;id=a1404f4703'

# Authors
authors:
  sal:
    name: Tomer
    display_name: Tomer
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: tomerbd1@gmail.com
    web: https://tomer-ben-david.github.io
    twitter: https://twitter.com/tomerbd1
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
